/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilStandardFirstAidOct_24 {
    name: string
    /**
     * Last 4 characters of NRIC/passport
     */
    partialNricOrPassport: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Course date of the certificate
     */
    courseDate: string
    /**
     * Course batch number
     */
    courseBatchNumber: string
    /**
     * Name of trainer
     */
    ciName: 'Darvin Bin Rozali'
    /**
     * CI's signature
     */
    ciSignature: 'darvin-bin-rozali-signature&88b24e2878675c1939b90322909ee5d40e1a36648fce0c29cb8ded459eb2d3b6.png'
    /**
     * Certificate number
     */
    certificateNumber: string
}
