/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfCompletion_2Signees {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee one
     */
    signeeOneName: string
    /**
     * Designation of signee one
     */
    signeeOneDesignation: string
    /**
     * Division of signee one
     */
    signeeOneDivision: string
    /**
     * Organisation of signee one
     */
    signeeOneOrganisation: string
    /**
     * Signature of signee one
     */
    signeeOneSignature_image: string
    /**
     * Name of signee two
     */
    signeeTwoName: 'Sahas Sankaran'
    /**
     * Designation of signee two
     */
    signeeTwoDesignation: 'Director'
    /**
     * Division of signee two
     */
    signeeTwoDivision: 'GovTech Digital Academy'
    /**
     * Organisation of signee two
     */
    signeeTwoOrganisation: 'Government Technology Agency'
    /**
     * SHA256 hash of the signee two's signature
     */
    signeeTwoSignature: 'sahas-sankaran-signature&d83beb8b8fe3c9a7efba8b80a693c4d58d33e4e94f1f4b556f13769742f861b9.svg'
}
