/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilStandardFirstAid {
    name: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Name of trainer
     */
    ciName: 'Fazdli Jamal' | 'Jaffar Ali'
    /**
     * CI's signature
     */
    ciSignature:
        | 'fazdli-jamal-signature&09fc5bfca94f8c519f9433c611b4fb9ff8cfed316343125469a8addee67c6b06.png'
        | 'jaffar-ali-signature&3d805f88bf49b640f6498c0e5335806289c24ee9533c7b79b08f3a5e454f1be4.png'
    /**
     * Certificate number
     */
    certificateNumber: string
}
