/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ForTestingMultipleImagesCertificate {
    imageOne_image: string
    levelTwo: {
        imageTwo_image: string
        imageThree_image: string
        levelThree: {
            imageFour_image: string
        }
    }
}
