/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechCrisprCop {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: 'Yap Ghim Eng'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Director of Data Engineering Practice'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'yap-ghim-eng-signature&d5385b8a7e5a66e9be2b8e942ead4c23d9392c196d77b93a1be24d5c94324986.png'
}
