[build]
  publish = "build/"

  # Default build command.
  command = "export REACT_APP_RENDERER_VERSION=ministry-of-communications-and-information_v0.0.0; CI=false yarn build ministry-of-communications-and-information"
