/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TrustdocsDemoDaCoc_1S {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: 'Sample_name2'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Director'
    /**
     * Division of signee
     */
    signeeDivision: 'GovTech Digital Academy'
    /**
     * Organisation of signee
     */
    signeeOrganisation: 'Government Technology Agency'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'demo_signature&73dc9d9d6712302c945fbb91d91cc65ef20f6b0d60a0665defbf7d418a506d33.png'
}
