/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfAchievementSmartnation {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    programmeStartDate: string
    /**
     * Date of issue
     */
    programmeEndDate: string
    /**
     * Name of signee
     */
    signeeName: 'Joseph Leong'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Permanent Secretary'
    /**
     * Organisation of signee
     */
    signeeOrganisation: 'Ministry of Digital Development and Information, Smart Nation, and Cybersecurity'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'joseph-leong-coa-signature&3f58615390f610d16d0dfdfb330cad21194eb768780cec807924ce66a321f821.png'
}
