/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDatCoa {
    /**
     * Name of participant
     */
    name: string
    /**
     * Awardee placement
     */
    awardPlacement:
        | 'Champion'
        | '1st Runner Up'
        | '2nd Runner Up'
        | 'Semi Finalist'
    /**
     * Award type
     */
    awardType: 'Prompt Royale Award' | 'VIZtory Award'
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: 'Chang Sau Sheong'
    /**
     * Designation of signee
     */
    signeeDesignation: 'DEPUTY CHIEF EXECUTIVE'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'chang-sau-sheong-signature&9b31b9f05b81bc64dfd2a9ecb412ed43297da93bf7c8708407954d1ac855ad96.png'
}
