/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SingaporeFoodAgencyExportHealthCertificate {
    /**
     * Certificate Number
     */
    certificateNumber: string
    /**
     * Exporting Country
     */
    exportingCountry: 'SINGAPORE'
    /**
     * @minItems 1
     * @maxItems 5
     */
    products:
        | [
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              }
          ]
        | [
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              }
          ]
        | [
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              }
          ]
        | [
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              }
          ]
        | [
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              },
              {
                  /**
                   * Product description
                   */
                  description: string
                  /**
                   * Product brand
                   */
                  brand: string
                  /**
                   * Product Code/Batch No./ Lot No.
                   */
                  codeOrBatchNoOrLotNo: string
                  /**
                   * Number & Type of Packages
                   */
                  numberAndTypeOfPackages: string
                  /**
                   * Net weight(Gross Weight)
                   */
                  netWeight: string
                  /**
                   * Production date in YYYY-MM-DD
                   */
                  productionDate: string
                  /**
                   * Expiry date in YYYY-MM-DD
                   */
                  expiryDate: string
              }
          ]
    /**
     * Means of Transport
     */
    meansOfTransport: string
    /**
     * Vessel Name/Flight Number
     */
    vesselNameFlightNumber: string
    /**
     * Container No.
     */
    containerNo: string
    /**
     * Seal No.
     */
    sealNo: string
    /**
     * Estimated time of departure in YYYY-MM-DD
     */
    etd: string
    /**
     * Place of Dispatch
     */
    placeOfDispatch: string
    /**
     * Shipping Marks
     */
    shippingMarks: string
    /**
     * Shipping Marks
     */
    remarks: string
    originAndProvenence: {
        /**
         * Name and Address of Manufacturer
         */
        nameAddressOfManufacturer: string
        /**
         * Processing Premise License No.
         */
        processingPremiseLicenseNo: string
        /**
         * Name and Address of Consignor
         */
        nameAddressOfConsignor: string
        /**
         * Date of inspection in YYYY-MM-DD
         */
        dateOfInspection: string
    }
    destination: {
        /**
         * Country/Region of Destination
         */
        countryRegionOfDestination: string
        /**
         * Name and Address of Consignee
         */
        nameAddressOfConsigee: string
        /**
         * Import Permit No.
         */
        importPermitNo: string
        /**
         * Purpose
         */
        purpose: string
    }
    attestation: {
        /**
         * Laboratory results
         */
        laboratoryResults: string
    }
    /**
     * Issued in Singapore date in YYYY-MM-DD
     */
    issuedInSingaporeDate: string
    /**
     * Name of signee
     */
    signeeName: string
    /**
     * Signature of signee
     */
    signeeSignature_image: string
}
