/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SingaporeJudicialCollegeCertificateOfCompletion {
    /**
     * Name of awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: string
    /**
     * Start date of course
     */
    courseStartDate: string
    /**
     * End date of course
     */
    courseEndDate: string
    /**
     * Issuance date of certificate
     */
    issuanceDate: string
    /**
     * Name of signee
     */
    signeeName: 'Sundaresh Menon'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Chief Justice'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'sample-signature&cacfb1e1c1af263245b1925f10eab6cb6bf675111478bb91e54ecd250482ce7c.png'
}
