/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SingaporeJudicialCollegeCertificateOfCompletion {
    /**
     * Name of awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: string
    /**
     * Start date of course
     */
    courseStartDate: string
    /**
     * End date of course
     */
    courseEndDate: string
    /**
     * Issuance date of certificate
     */
    issuanceDate: string
    /**
     * Name of signee
     */
    signeeName: 'Natalie Skead'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Dean'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'natalie-skead-signature&195bd78f3c419e8ec21d3d364f50f703e85d43c401639a628d0119b7cbefd935.png'
}
