/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfCompletionSmartnation {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: 'Joseph Leong'
    /**
     * Designation of signee
     */
    signeeDesignation: 'Permanent Secretary'
    /**
     * Organisation of signee
     */
    signeeOrganisation: 'Smart Nation and Digital Government Group'
    /**
     * SHA256 hash of the signee's signature
     */
    signeeSignature: 'joseph-leong-signature&6bb7c9981a0e17da0609cf3722b244af0006e585d7dc5a293f2383689303672d.png'
    [k: string]: unknown
}
