/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CsaMilestone {
    /**
     * Name of awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: string
    /**
     * Start date of course
     */
    courseStartDate: string
    /**
     * End date of course
     */
    courseEndDate: string
    /**
     * list of presenters jointly presenting the award
     */
    presentedBy: string[]
    signatureOne: {
        /**
         * owner of signature
         */
        name: string
        /**
         * title of owner of signature
         */
        title: string
        /**
         * organization of owner of signature
         */
        organization: string
        /**
         * Hash of the signature's image file
         */
        signatureHash: string
        additionalProperties?: false
        [k: string]: unknown
    }
    signatureTwo: {
        /**
         * owner of signature
         */
        name: string
        /**
         * title of owner of signature
         */
        title: string
        /**
         * organization of owner of signature
         */
        organization: string
        /**
         * Hash of the signature's image file
         */
        signatureHash: string
        additionalProperties?: false
        [k: string]: unknown
    }
    additionalProperties?: false
    [k: string]: unknown
}
