/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilObsWmfr {
    name: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Serial number
     */
    serialNumber: string
    /**
     * Name of the issuing officer
     */
    issuingOfficerName: string
    /**
     * Position of the issuing officer
     */
    issuingOfficerPosition: string
    /**
     * Image hash value of the issuing officer's signature
     */
    issuingOfficerSignature: string
    additionalProperties?: false
    [k: string]: unknown
}
