/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilStandardFirstAid {
    name: string
    /**
     * NRIC of the recipient
     */
    nric: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Name of trainer
     */
    trainerName: string
    /**
     * CI's signature
     */
    ciSignature: string
    /**
     * Certificate number
     */
    serialNumber: string
}
