/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilObsWmfrOct_24 {
    name: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Course date of the certificate
     */
    courseDate: string
    /**
     * Course code
     */
    courseCode: string
    /**
     * Certificate number
     */
    certificateNumber: string
    /**
     * Name of the issuing officer
     */
    ExecDirName: 'Nicholas Conceicao' | 'Dr Ng Yih Yng'
    /**
     * Image hash value of the issuing officer's signature
     */
    ExecDirSignature:
        | 'nicholas-signature&1e6ebedbff42703518a83c1b296744c55f071f9147ec19c8ebae88794ab3f120.png'
        | 'dr-yih-yng-signature&87961f1e6b1874d14eb157e78a680108cef21cfba862592973d5445b9d4d7495.png'
}
