/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TrustdocsDemoLicenseToVerify {
    /**
     * Name of the recipient
     */
    name: string
    /**
     * Filename of the profile image
     */
    profile_image: string
    /**
     * Date of issue
     */
    issuedOn: string
    /**
     * Last date of validity
     */
    validTill: string
    /**
     * Country of accessment
     */
    countryOfAccessment: string
    /**
     * Name of person who accessed
     */
    accessedBy: string
    qrCodeValue: string
}
