/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ForTestingSimpleCert_2 {
    /**
     * Name of awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: string
    /**
     * Start date of course
     */
    courseStartDate: string
    /**
     * End date of course
     */
    courseEndDate: string
    /**
     * Certificate number
     */
    serialNumber: string
}
