/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MindefMindefPdf {
    /**
     * Name of participant
     */
    name: string
    /**
     * Name of this document
     */
    documentName:
        | 'Certificate of Service Package'
        | 'Certificate of Service'
        | 'Transcript'
        | 'Testimonial'
        | 'Transcript and Testimonial'
    /**
     * Reference number
     */
    referenceNo: string
    /**
     * input pdf filename
     */
    input_pdf: string
}
