/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilTechnicalSkills {
    /**
     * Name of the awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: string
    /**
     * Date of the course
     */
    courseDate: string
    /**
     * Name of the organisation representation
     */
    organisationRepName: string
    /**
     * Title of the organisation representation
     */
    organisationRepTitle: string
    /**
     * SHA256 hash of the organisation representation's signature
     */
    organisationRepSignature: 'nicholas-signature&1e6ebedbff42703518a83c1b296744c55f071f9147ec19c8ebae88794ab3f120.png'
    /**
     * Description of the course
     */
    courseDescription: string
}
