/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfAchievement_1SigneeV2 {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee one
     */
    signeeOneName: 'Patrick Pang'
    /**
     * Designation of signee one
     */
    signeeOneDesignation: 'Director'
    /**
     * Division of signee one
     */
    signeeOneDivision: 'GovTech Digital Academy'
    /**
     * Organisation of signee one
     */
    signeeOneOrganisation: 'Government Technology Agency'
    /**
     * SHA256 hash of the signee one's signature
     */
    signeeOneSignature: 'patrick-pang-signature&39573e7f99ce6836b3fc4785dc6d2071b037fe9926fc9133b08aaabab40451a4.png'
}
