/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HealthSciencesAuthorityHsaShareCertificate_1YExpiry {
    /**
     * Name of the receiving oraganisation
     */
    organisationName: string
    /**
     * Document name
     */
    documentName: string
    /**
     * Document reference
     */
    documentReference: string
    /**
     * Name of SAL officer
     */
    signatoryName: string
    /**
     * Designation of SAL officer
     */
    signatoryDesignation: string
    /**
     * Agency name for the SAL e-apostille
     */
    agencyName: 'Health Sciences Authority'
    /**
     * Expiry date of permit
     */
    validUntil: string
    /**
     * input pdf filename or base64 encoded string
     */
    pdfContent_pdf: string
}
