/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechStack_2024CertificateOfCompletion {
    /**
     * Name of recipient
     */
    name: string
    /**
     * Workshop's title
     */
    workshopTitle: string
    /**
     * Trainer Name
     */
    trainerName: string
    /**
     * Organisation
     */
    organisation: string
    /**
     * Filename of signature
     */
    signature_image: string
}
