/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SkillsfutureSingaporeMsfCsp {
    /**
     * Registrant name
     */
    name: string
    /**
     * Date of issue in YYYY-MM-DD
     */
    issueDate: string
    /**
     * Date of expiry in YYYY-MM-DD
     */
    expiryDate: string
    topSkills: {
        /**
         * Display order on MySkillsFuture Skills Passport
         */
        displayOrder: number
        skills: {
            /**
             * Skill Type
             */
            type: 'CERTIFIED' | 'SELF_DECLARED' | 'INFERRED'
            /**
             * Short name of Skill
             */
            shortName: string
            /**
             * Full name of Skill
             */
            fullName: string
            /**
             * Source of Skill
             */
            acquiredFrom?: string
        }[]
    }
    employmentHistory: {
        /**
         * Display order on MySkillsFuture Skills Passport
         */
        displayOrder: number
        positions: {
            isVerifiedEmployee: boolean
            /**
             * Title of position
             */
            position: string
            /**
             * Name of employer
             */
            employer: string
            /**
             * Period of employment
             */
            period: string
        }[]
    }
    professionalCertifications: {
        /**
         * Display order on MySkillsFuture Skills Passport
         */
        displayOrder: number
        certifications: {
            isVerified: boolean
            /**
             * Title of professional certification
             */
            certificateTitle: string
            /**
             * Source of professional certification
             */
            source: string
            /**
             * Date attained of professional certification
             */
            dateAttained: string
        }[]
    }
    academicQualifications: {
        /**
         * Display order on MySkillsFuture Skills Passport
         */
        displayOrder: number
        qualifications: {
            isVerified: boolean
            /**
             * Title of qualification
             */
            qualificationTitle: string
            /**
             * Source of professional certification
             */
            source: string
            /**
             * Date attained of academic qualification
             */
            dateAttained: string
        }[]
    }
}
