/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechLaunchHackathon {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Title of the award
     */
    awardTitle: string
    /**
     * Description of the award
     */
    awardDescription: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: string
    /**
     * Designation of signee
     */
    signeeDesignation: string
    /**
     * Sigature of signee
     */
    signeeSignature_image: string
    /**
     * Image of the partnership logo
     */
    partnershipLogo_image: string
}
