/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HealthSciencesAuthorityMethodValidationForChemicalTesting {
    /**
     * Name of awardee
     */
    name: string
    /**
     * Title of the course
     */
    courseTitle: 'Method Validation for Chemical Testing'
    /**
     * End date of course
     */
    courseEndDate: string
    /**
     * Name of signee
     */
    signeeName: string
    /**
     * Designation of signee
     */
    signeeDesignation: string
    /**
     * Division of signee
     */
    signeeDivision: string
    /**
     * Group of signee
     */
    signeeGroup: string
    /**
     * Organisation of signee
     */
    signeeOrganisation: 'Health Sciences Authority'
    /**
     * Signature of signee
     */
    signeeSignature_image: string
}
