/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TrustdocsDemoDemoPermit {
    /**
     * Name of recipient
     */
    name: string
    /**
     * Effective date of permit
     */
    effectiveDate: string
    /**
     * Expiry date of permit
     */
    expiryDate: string
    /**
     * Address line 1
     */
    addressLineOne: string
    /**
     * Address line 2
     */
    addressLineTwo: string
    /**
     * base64 data uri of logo image, but filename if it is excel upload flow
     */
    logo_image?: string
}
