/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilBclsAed {
    name: string
    /**
     * NRIC of the recipient
     */
    nric: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Name of trainer
     */
    trainerName: string
    /**
     * CI's signature
     */
    ciSignature: 'ci-signature&1e4008a9529d7f62affa65d71ca40f9e92fe15041b9e77d331ec5a839217fdfc.png'
    /**
     * Certificate number
     */
    serialNumber: string
}
