/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfParticipationV2_1Signee {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee two
     */
    signeeOneName: 'Sahas Sankaran'
    /**
     * Designation of signee two
     */
    signeeOneDesignation: 'Director'
    /**
     * Division of signee two
     */
    signeeOneDivision: 'GovTech Digital Academy'
    /**
     * Organisation of signee two
     */
    signeeOneOrganisation: 'Government Technology Agency'
    /**
     * SHA256 hash of the signee two's signature
     */
    signeeOneSignature: 'sahas-sankaran-signature&d83beb8b8fe3c9a7efba8b80a693c4d58d33e4e94f1f4b556f13769742f861b9.svg'
}
