/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilCciLevel_1 {
    name: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Course date
     */
    courseDate: string
    /**
     * Name of Duty Programme Officer
     */
    dutyProgrammeOfficerName: string
    /**
     * Duty Programme Officer's signature
     */
    dutyProgrammeOfficerSignature: 'nicholas-signature&1e6ebedbff42703518a83c1b296744c55f071f9147ec19c8ebae88794ab3f120.png'
    /**
     * Certificate number
     */
    serialNumber: string
}
