/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TrustdocsDemoNycSfa {
    name: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Name of trainer
     */
    ciName: 'Sample_name2'
    /**
     * CI's signature
     */
    ciSignature: 'demo_signature&73dc9d9d6712302c945fbb91d91cc65ef20f6b0d60a0665defbf7d418a506d33.png'
    /**
     * Certificate number
     */
    certificateNumber: string
}
