/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GovtechDigitalAcademyCertificateOfAchievement_2SigneesV2 {
    /**
     * Name of participant
     */
    name: string
    /**
     * Title of the programme
     */
    programmeTitle: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Name of signee one
     */
    signeeOneName: string
    /**
     * Designation of signee one
     */
    signeeOneDesignation: string
    /**
     * Division of signee one
     */
    signeeOneDivision: string
    /**
     * Organisation of signee one
     */
    signeeOneOrganisation: string
    /**
     * Signature of signee one
     */
    signeeOneSignature_image: string
    /**
     * Name of signee two
     */
    signeeTwoName: 'Patrick Pang'
    /**
     * Designation of signee two
     */
    signeeTwoDesignation: 'Director'
    /**
     * Division of signee two
     */
    signeeTwoDivision: 'GovTech Digital Academy'
    /**
     * Organisation of signee two
     */
    signeeTwoOrganisation: 'Government Technology Agency'
    /**
     * SHA256 hash of the signee two's signature
     */
    signeeTwoSignature: 'patrick-pang-signature&39573e7f99ce6836b3fc4785dc6d2071b037fe9926fc9133b08aaabab40451a4.png'
    /**
     * Logo of partner
     */
    partnerLogo_image: string
}
