/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalParksBoardQuarantineAndVaccinationCertificate {
    /**
     * Name of animal
     */
    animalName: string
    /**
     * Microchip of animal
     */
    microchipNumber: string
    /**
     * Species of animal
     */
    species: string
    /**
     * Breed of animal
     */
    breed: string
    /**
     * Date of birth of animal
     */
    birthDate: string
    /**
     * Sex of animal
     */
    sex: 'male' | 'female'
    /**
     * Color of animal
     */
    colour: string
    /**
     * Country of export
     */
    exportCountry: string
    /**
     * Name of owner
     */
    name: string
    quarantine: {
        numOfDays: number
        /**
         * Start date of quarantine in YYYY-MM-DD
         */
        startDate: string
        /**
         * End date of quarantine in YYYY-MM-DD (inclusive)
         */
        endDate: string
    }
    rabiesVaccination?: {
        /**
         * Manufacturer of vaccine
         */
        manufacturer: string
        /**
         * Date of vaccination
         */
        date: string
        /**
         * Duration of validity
         */
        validityDuration: string
        batch: {
            /**
             * Batch number
             */
            number: string
            /**
             * Expiry of batch
             */
            expiry: string
        }
        /**
         * Veterinarian that administered vaccine
         */
        veterinarian: string
    }
}
