#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn process:images
yarn process:schemas
yarn process:headers
git add public/_headers
git add src/**/*/__generated__/*
yarn lint-staged
yarn typecheck
