#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run process:images
npm run process:schemas
npm run process:headers
git add public/_headers
git add src/**/*/__generated__/*
npm run lint-staged
npm run typecheck
