/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilBclsAedOct_24 {
    name: string
    /**
     * Last 4 characters of NRIC/passport
     */
    partialNricOrPassport: string
    /**
     * Issuance date of the certificate
     */
    issueDate: string
    /**
     * Course batch number
     */
    courseBatchNumber: string
    /**
     * Name of trainer
     */
    ciName: 'Jaffar Ali'
    /**
     * CI's signature
     */
    ciSignature: 'jaffar-ali-signature&3d805f88bf49b640f6498c0e5335806289c24ee9533c7b79b08f3a5e454f1be4.png'
    /**
     * Certificate number
     */
    certificateNumber: string
}
