/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NationalYouthCouncilObsWmfr {
    name: string
    /**
     * Date of issue
     */
    issueDate: string
    /**
     * Certificate number
     */
    certificateNumber: string
    /**
     * Name of the issuing officer
     */
    ExecDirName: 'Nicholas Conceicao'
    /**
     * Image hash value of the issuing officer's signature
     */
    ExecDirSignature: 'nicholas-signature&1e6ebedbff42703518a83c1b296744c55f071f9147ec19c8ebae88794ab3f120.png'
}
