/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TrustdocsDemoLicenseToVerifyTrial {
    /**
     * Name of recipient
     */
    name: string
    /**
     * Filename of the profile image
     */
    profile_image: string
    /**
     * Date of issue
     */
    issuedOnDate: string
    /**
     * Date of expiry
     */
    validTillDate: string
    /**
     * Name of assessor
     */
    assessorName: string
    /**
     * Contry of assessment
     */
    countryOfAssessment: 'Singapore'
}
