/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MindefCertificateOfService {
    /**
     * Name of participant
     */
    name: string
    /**
     * Reference number
     */
    referenceNo: string
    /**
     * Date of Issue
     */
    issueDate: string
    /**
     * Name of signee
     */
    signeeName: string
    /**
     * Designation of signee
     */
    signeeDesignation: string
    /**
     * Department of signee
     */
    signeeDepartment: string
    /**
     * Signature of signee
     */
    signeSignature_image: string
}
